### ISSUE TITLE
构建v8源码

### ISSUE THREAD

**Issue by huenchao** [huenchao/v8_translate#2]
这篇文章会教你怎么在本地玩弄你的v8源码。

### 第一步就是获取v8代码

以下所有操作步骤的前置条件，是你要会**翻墙**，反正把你的vpn开起来，然后配置好git的http.proxy、https.proxy,以及环境变量http_proxy、https_proxy。当然就算你配置好了，这个速度也还是很感人了，我花了40分钟才下载下来。。。
```git
git config --global http.proxy http://localhost:1085
git config --global https.proxy http://localhost:1085
export http_proxy=http://localhost:1085
export https_proxy=http://localhost:1085
```

1. 如果你是 Linux 或者 macOS用户，你先要安装git，再安装 depot_tools。
2. 然后在终端运行如下命令来更新你的depot_tools。
```bash
gclient
```
3. 第三步就先忽略吧，是教你怎么配置push v8代码权限的。
4. 获取v8代码。
```bash
mkdir ~/v8
cd ~/v8
fetch v8
cd v8
```

![image](https://user-images.githubusercontent.com/14048126/79985952-e8682680-84dd-11ea-8198-314fae1a2940.png)

5. 完成上面4步后，你将进入一个游离分支的状态，官方推荐你基于这个commit新建一个分支，比如我这样：
```git 
git new-branch study_v8
```
![image](https://user-images.githubusercontent.com/14048126/79987837-79d89800-84e0-11ea-8fbd-c12bfbe85aaf.png)

**Comment by huenchao** [comment]
### 第二步就是安装构建依赖
1. 安装Xcode和证书。
2. 确保你现在在v8目录下，如果你完成了第一步。
3. 下载各种构建依赖。
4. 如果你是linux用户，你需要运行下面的命令安装额外的依赖。
```bash
./build/install-build-deps.sh
```

**Comment by huenchao** [comment]
### 第三步就是编译
1. gclient sync
2. tools/dev/gm.py x64.release
当然如果你运行第二步的时候报错了，类似如下的错误:
```bash
# mkdir -p out/x64.release
# echo > out/x64.release/args.gn << EOF
is_component_build = false
is_debug = false
target_cpu = "x64"
use_goma = false
goma_dir = "None"
v8_enable_backtrace = true
v8_enable_disassembler = true
v8_enable_object_print = true
v8_enable_verify_heap = true
EOF
# gn gen out/x64.release
ERROR at //build/config/mac/mac_sdk.gni:114:5: Script returned non-zero exit code.
    exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
    ^----------
Current dir: /Users/huenchao/studys/v8/v8/out/x64.release/
Command: python /Users/huenchao/studys/v8/v8/build/mac/find_sdk.py --print_sdk_path --print_bin_path 10.15
Returned 1.
stderr:

Traceback (most recent call last):
  File "/Users/huenchao/studys/v8/v8/build/mac/find_sdk.py", line 127, in <module>
    print(main())
  File "/Users/huenchao/studys/v8/v8/build/mac/find_sdk.py", line 96, in main
    raise Exception('No %s+ SDK found' % min_sdk_version)
Exception: No 10.15+ SDK found

See //build/toolchain/mac/BUILD.gn:15:1: whence it was imported.
import("//build/config/mac/mac_sdk.gni")
^--------------------------------------
See //BUILD.gn:917:1: which caused the file to be included.
action("postmortem-metadata") {
^------------------------------
Error! - V8 compilation finished with errors.
```

放弃吧，我建议你直接选个低版本的tag，重新切个分支再重来一遍。我是参考hyj的那个tag。

**Comment by huenchao** [comment]
参考文献：
https://v8.dev/docs/build
https://zhuanlan.zhihu.com/p/102316528
